<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
class Spkh extends Model
{
    protected $table = 'spkh';
    protected $fillable = [
        'tgl',
        'nojnl',
        'bukti',
        'qty',
        'note',
        'post',
        'modifyby',
        'modifyon',
        'kodeinv',
        'kodecust',
        'fgroup',
        'gud',
        'qtyo',
        'sisa',
        'ukr1',
        'ukr2',
        'ref',
        'reftgl',
        'tglkirim',
        'fno',
        'djoin',
        'qtyp',
        'lkertas',
        'out',
        'tol',
        'lmeter',
        'qpaku',
        'berat1',
        'berat2',
        'berat3',
        'berat4',
        'berat5',
        'twaste',
        'nprint',
        'hcorr',
        'hflexo',
        'hdc',
        'hlilin',
        'hstich',
        'hglue',
        'qtyr',
        'pkwa',
        'obstat',
        'hlongway',
        'appprinton',
        'appprintby',
        'ref1',
        'fno1',
        'fprint',
        'tgi1',
        'tgi2',
        'tgi3',
        'librpl',
        'hhts',
        'dpqty',
        'dlqty',
        'batal',
        'prodstat',
        'hstgl',
        'kpx',
        'pj1',
        'lb1',
        'pj1',
        'lb1',
        'pj2',
        'lb2',
        'kp',
        'kptgl',
        'hari',
        'tglprod',
        'kodekrm',
        'luas',
        'berat',
        'beratb',
        'counter',
        'qtystock',
        'periode',

    ];
}
